# Generated by Django 3.2.6 on 2021-08-27 03:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionRewards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rarity', models.CharField(max_length=255)),
                ('chance', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
