# Generated by Django 3.2.6 on 2021-08-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframedrop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionrewards',
            name='gameMode',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionrewards',
            name='isEvent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionrewards',
            name='mission',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionrewards',
            name='planet',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionrewards',
            name='rotation',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
