# Generated by Django 3.2.6 on 2021-08-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframedrop', '0002_auto_20210827_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrewards',
            name='chance',
            field=models.FloatField(),
        ),
    ]
